/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.
import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { createHandlerBoundToURL, precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { NetworkFirst } from "workbox-strategies";

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith("/_")) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
);

// Add a custom route for the root URL to redirect to badvisor.io/app
// registerRoute(
//   ({ url }) => url.origin === self.location.origin && url.pathname === "/",
//   async ({ request, url }) => {
//     const path = url.pathname === "/" ? "/" : url.pathname; // Replace '/app' with the default path
//     return Response.redirect(`https://badvisor.io${path}`, 302);
//   }
// );

// registerRoute(
//   ({ url }) => url.origin === self.location.origin,
//   async ({ request, url }) => {
//     const path = url.pathname;
//     const redirectPath = path === "/" ? "/kidsafghkjsdafgdsa/dsfhjgjdhsgf/skjdfhgjd" : path; // Replace '/your-specific-path' with your desired default path
//     return Response.redirect(`https://app.badvisor.io${redirectPath}`, 302);
//   }
// );

const fileTypesToCache = ["document", "script", "style", "image", "font", "manifest", "media", "model"];

//CACHE FIRST
// fileTypesToCache.forEach((fileType) => {
//   registerRoute(
//     ({ request }) => request.destination === fileType,
//     new CacheFirst({
//       cacheName: `badvisor-cache`,
//       cacheName: `badvisor-static-cache`,
//       plugins: [
//         new ExpirationPlugin({
//           maxEntries: 999, // 60
//           maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
//         }),
//       ],
//     })
//   );
// });

//NET FIRST
fileTypesToCache.forEach((fileType) => {
  registerRoute(
    ({ request }) => request.destination === fileType,
    new NetworkFirst({
      cacheName: `badvisor-static-cache`,
      plugins: [
        new ExpirationPlugin({
          maxEntries: 999, // 60
          maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
        }),
      ],
    })
  );
});

// CACHE FIRST
// self.addEventListener("fetch", (event) => {
//   event.respondWith(
//     caches.open("badvisor-fetch-cache").then((cache) => {
//       return cache
//         .match(event.request)
//         .then((response) => {
//           if (response) {
//             return response;
//           }

//           return fetch(event.request).then((networkResponse) => {
//             if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== "basic") {
//               return networkResponse;
//             }

//             const responseToCache = networkResponse.clone();

//             caches.open("badvisor-fetch-cache").then((cache) => {
//               cache.put(event.request, responseToCache);
//             });

//             return networkResponse;
//           });
//         })
//         .catch((error) => {
//           // Handle fetch errors here
//           console.error("Error in fetching: ", error);
//         });
//     })
//   );
// });

// NET FIRST
self.addEventListener("fetch", (event) => {
  event.respondWith(
    fetch(event.request)
      .then((networkResponse) => {
        if (networkResponse && networkResponse.status === 200 && networkResponse.type === "basic") {
          const responseToCache = networkResponse.clone();
          caches.open("badvisor-fetch-cache").then((cache) => {
            cache.put(event.request, responseToCache);
          });
        }
        return networkResponse;
      })
      .catch((error) => {
        return caches.match(event.request).then((response) => {
          if (response) {
            return response;
          }
          // Handle fetch errors here
          console.log("Error in fetching: ", error);
        });
      })
  );
});

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
